"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KENYAN_COUNTIES = exports.PROPERTY_FEATURES = exports.COMMON_AMENITIES = exports.PROPERTY_AMENITIES = exports.PROPERTY_CATEGORIES = void 0;
// Common property types as categories
exports.PROPERTY_CATEGORIES = [
    { id: 'houses', name: 'Houses', description: 'Family homes & villas' },
    { id: 'apartments', name: 'Apartments', description: 'Modern complexes' },
    { id: 'one_bedroom', name: '1 Bedroom', description: 'Perfect for singles' },
    { id: 'two_bedroom', name: '2 Bedroom', description: 'Ideal for couples' },
    { id: 'three_bedroom', name: '3 Bedroom', description: 'Family friendly' },
    { id: 'bedsitters', name: 'Bedsitters', description: 'Studio living' },
    { id: 'commercial', name: 'Commercial', description: 'Shops & offices' },
    { id: 'industrial', name: 'Industrial', description: 'Warehouses & parks' },
    { id: 'offices', name: 'Offices', description: 'Business centers' },
    { id: 'land_plots', name: 'Land/Plots', description: 'Plots & acreage' },
];
// Common amenities and features
exports.PROPERTY_AMENITIES = [
    'Swimming Pool',
    'Gym',
    'Security',
    'Parking',
    'Generator',
    'Borehole',
    'Garden',
    'Balcony',
    'DSTV',
    'Internet',
    'Elevator',
    'Fire Safety',
    'CCTV',
    'Playground',
    'Shopping Center',
    'Hospital',
    'School',
];
// Alias expected by some helpers
exports.COMMON_AMENITIES = exports.PROPERTY_AMENITIES;
exports.PROPERTY_FEATURES = [
    'Furnished',
    'Semi-Furnished',
    'Unfurnished',
    'Newly Built',
    'Renovated',
    'Air Conditioning',
    'Kitchen Cabinets',
    'Water Heater',
    'Backup Water',
    'Gated Community',
    'Corner Plot',
    'Main Road',
    'Quiet Neighborhood',
];
// Kenyan counties for location filtering
exports.KENYAN_COUNTIES = [
    'Nairobi',
    'Mombasa',
    'Nakuru',
    'Kiambu',
    'Machakos',
    'Kajiado',
    'Murang\'a',
    'Nyeri',
    'Kirinyaga',
    'Nyandarua',
    'Laikipia',
    'Meru',
    'Tharaka Nithi',
    'Embu',
    'Kitui',
    'Kakamega',
    'Bungoma',
    'Busia',
    'Siaya',
    'Kisumu',
    'Homa Bay',
    'Migori',
    'Kisii',
    'Nyamira',
    'Trans Nzoia',
    'Uasin Gishu',
    'Elgeyo Marakwet',
    'Nandi',
    'Baringo',
    'Kericho',
    'Bomet',
    'West Pokot',
    'Samburu',
    'Turkana',
    'Isiolo',
    'Marsabit',
    'Mandera',
    'Wajir',
    'Garissa',
    'Tana River',
    'Lamu',
    'Taita Taveta',
    'Kwale',
    'Kilifi',
];
